<?php
	/* include the jQuery in here, so it's all together <?php bloginfo('template_directory');?> */
	// the "deck" of Strategies
	$deck = array(
		"(organic) Machinery.",
		".esreveR",
		"Abandon desire.",
		"Abandon normal instructions.",
		"Abandon normal instruments.",
		"Accretion.",
		"A line has 2 sides.",
		"Allow an easement. (An easement is the abandonment of a stricture.)",
		"Always first steps.",
		"Ask for advice.<br />Accept some advice.<br />Don't question it.",
		"Ask for advice.<br />Accept some advice.<br />Do the exact opposite of it.",
		"Ask people to work against their better judgment.",
		"Ask your body.",
		"Assume a contrary norm.",
		"A very small object. It's centre.",
		"Back up.",
		"Balance the consistency principle with the inconsistency principle.",
		"Be dirty.",
		"Be extravagant.",
		"Before. And After.",
		"Be less critical more often.",
		"Blank space is more important.",
		"Break it apart.",
		"Breathe more deeply.",
		"Bridges:<br />-build<br />-burn",
		"cascades",
		"Change instrumental roles.",
		"Change nothing and continue with immaculate consistency.",
		"Cluster analysis.",
		"Consider different fading systems.",
		"Consider transitions.",
		"Courage!",
		"Cut a vital connection.",
		"Define an areas as \"safe\" and use it as an anchor.",
		"Describe the landscape in which this belongs.",
		"Destroy:<br />-nothing<br />-the most important thing",
		"Discard an axiom.",
		"Disciplined self-indulgence.",
		"Disconnect from desire.",
		"Distorting time.",
		"Does it have more than 1 way to look?",
		"Do nothing for as long as possible.",
		"Don't be afraid of cliches.",
		"Don't be afraid of things because they're easy to do.",
		"Don't be frightened to display your talents.",
		"Don't break the silence.",
		"Don't stress one thing more than another.",
		"Do something boring.",
		"Do something that's just plain wrong.",
		"Do the words need changing?",
		"Do we need holes?",
		"Emphasize differences.",
		"Emphasize repetitions.",
		"Emphasize the absent.",
		"Emphasize the flaws.",
		"Exist as a single unrepeatable moment in time.",
		"Faced with a choice, do both.",
		"Feed the recording back out of the medium.",
		"Fill every beat with something.",
		"Find the part you like the most.",
		"Find your voice by imitating others.",
		"Find your voice, then immediately begin searching for a clearer one.",
		"First work alone. Then work in unusual pairs.",
		"Forget the building.<br />Forget the wall.<br />Make a brick.",
		"From nothing to more than nothing.",
		"Get a massage.",
		"ghost echoes",
		"Give the game away.",
		"Give way to your worst impulse.",
		"Go outside. Shut the door.",
		"Go slowly all the way around the outside.",
		"Go to an extreme, then move back to a more comfortable place.",
		"Honor thy error as a hidden intention.",
		"How would YOU have done it?",
		"Humanize something free of error.",
		"Idiot glee.",
		"If you can't hide something, decorate it.",
		"If your hero wouldn't do it, now's your chance.",
		"I know it's too much, but is it enough?",
		"Imagine the piece as a set of disconnected events.",
		"Infinitesimal gradations.",
		"Instead of changing the thing, change the world around it.",
		"Into the impossible.",
		"Is something missing?",
		"It's easy to be Buddhist when you have<br />-everything<br />-nothing.",
		"Listen in total darkness, or in a very large room, very quietly.",
		"Listen to the quiet voice.",
		"Look at the order in which you do things.",
		"Look closely at the most embarrassing details and amplify them.",
		"Lost in useless territory.",
		"Lowest Common Denominator.",
		"Make a blank valuable by putting it in an exquisite frame.",
		"Make an exhaustive list of everything you might do. Then do the last thing on that list.",
		"Make a sudden, destructive, unpredictable action: incorporate.",
		"Make the mistakes more important.",
		"Mechanicalize something idiosyncratic.",
		"Mute and continue.",
		"Once the search is in progress, something will be found.",
		"Only one (1) element of each kind.",
		"Overtly resist change.",
		"Pay attention to distractions.",
		"Pay attention to what you really want this line to say.",
		"Plow ahead.",
		"Question the heroic approach.",
		"Question the -nobility -humility -credibility of your intentions.",
		"Remove ambiguities and convert to specifics.",
		"Remove specifics and convert to ambiguities.",
		"Remove the middle, extend the edges.",
		"Repetition is a form of change.",
		"Rescue your sense of defeat.",
		"Retrace your steps.",
		"Reverse the order of your jobs.",
		"Revolution!  Change yourself.",
		"SEARCH! Don't care what you find.",
		"SHORT CIRCUIT (example: a man eating peas with the belief that they will improve his virility shovels them straight into his lap)",
		"simple substraction",
		"Slow preparation. Fast execution.",
		"Spectrum analysis.",
		"State the problem in words as simply as possible.",
		"Steal a solution.",
		"Take a nice break. Refresh.",
		"Take away as much mystery as possible. What is left?",
		"Take away the elements in order of apparent non-importance.",
		"The inconsistency principle.",
		"The most important thing is the most easily forgotten.",
		"The past happened while you were out.",
		"The sound of children.",
		"Think -inside the work -outside the work",
		"Throw away the cookbooks you're working from.",
		"Tidy up.",
		"Towards the (in)significant.",
		"TRAVEL. Your habits are never so obvious as when those around you change.",
		"Trust the artist you are right now.",
		"Try faking it.",
		"Turn it upside down.",
		"Twist the spine.",
		"Use an old idea.",
		"Use an unacceptable color.",
		"Use fewer notes.",
		"Use filters.",
		"Use \"unqualified\" people.",
		"Voice your suspicions.",
		"w  a  t  e  r",
		"What are the sections sections of? (Imagine a caterpillar moving.)",
		"What else is this like?",
		"What is the reality of the situation.",
		"What mistakes did you make last time?",
		"What to increase? What to reduce? What to maintain?",
		"What would a baby do?",
		"What wouldn't you do?",
		"When is it for?",
		"Where is the edge?",
		"Which parts can be grouped?",
		"Whose rules are you playing by, anyway?",
		"Work at a different speed.",
		"Would anybody want it?",
		"Would your best friend do it another way?",
		"You can only make one dot at a time.",
		"You don't need to be ashamed of using your own ideas.",
		"You have good ideas. Really."
	);
	
	function getOblique( $food ) {
		return $food[rand(0,(count($food)-1))];
	}
?>
<?php echo getOblique($deck); ?>